type Blog {
    date: String!
    message: String!
    title: String!
}

type Menu {
    href: String
    title: String!
    to: String
}

type Query {
    blog(offset: Int!, limit: Int!): [Blog]
    menu: [Menu]
}
